# Generated by Django 4.0.4 on 2022-06-09 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdl_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('co_driver_id', models.IntegerField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('vin_number', models.CharField(max_length=20, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off duty'), ('SB', 'Sleeper berth'), ('DR', 'Driving'), ('ON', 'On duty'), ('YM', 'Yard moves'), ('PC', 'Personal conveyance')], default='OFF', max_length=3)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('loc_name', models.CharField(max_length=50, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('odometer', models.IntegerField(null=True)),
                ('eng_hours', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('notes', models.CharField(max_length=20, null=True)),
                ('document', models.CharField(max_length=20, null=True)),
                ('trailer', models.CharField(max_length=20, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sameld.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sameld.vehicle')),
            ],
        ),
    ]
