# Generated by Django 4.0.4 on 2022-06-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sameld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='co_driver_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='co_driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sameld.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company_user_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sameld.vehicle'),
        ),
    ]
