# Generated by Django 4.0.4 on 2022-06-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sameld', '0003_driver_cdl_state_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='co_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sameld.driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_user_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sameld.vehicle'),
        ),
    ]
