# Generated by Django 4.0.4 on 2022-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sameld', '0004_alter_driver_co_driver_alter_driver_company_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='app_version',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
